apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: interested-lark-python 
  janus-idp.io/tekton: interested-lark-python
  backstage.io/kubernetes-id: interested-lark-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: interested-lark-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  